### ISSUE TITLE
AESKEY_OFFSETS如何自己分析？

### ISSUE THREAD

**Issue by mgttt** [lich0821/WeChatDB#1]
请问偏移有简单的计算查找办法吗？

**Comment by lich0821** [comment]
有的。
先选一个有偏移的版本，比如`3.7.5.23`，然后通过偏移（`0x242413C`）找到密码，再安装目标版本，然后通过刚才的密码，找到偏移。
![Desc](https://github.com/lich0821/WeChatDB/assets/87742696/3faf2faf-b91a-4124-96cf-49c6ae5e978b)
