### ISSUE TITLE
拿到的密钥怎么在工具里或程序里使用？

### ISSUE THREAD

**Issue by qiba** [lich0821/WeChatDB#9]
拿到了密钥，同时也能把库给解密出来。现在想在程序里或者 DB Browser for SQLite 工具里直接访问加密库，好像不行呢？如下图带入拿到的密钥也打不开数据库？
![11111](https://github.com/lich0821/WeChatDB/assets/3041572/9c4b7d17-fc29-47b3-a0ed-23ae03ba8001)

**Comment by lich0821** [comment]
[CrackWeChatDB.py](https://github.com/lich0821/WeChatDB/blob/master/CrackWeChatDB.py)
